title: JavaScript Tutorial
description: Learn JavaScript from scratch
baseurl: "" 
url: "https://mikedanielx.github.io" # change to your GitHub Pages URL

theme: minima # we'll customize it
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-toc

collections:
  pages:
    output: true
    permalink: /:name/
