name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # This is a Linux machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.0'

      - name: Install build tools and Protocol Buffers libraries
        # This command installs the necessary software for building gems from scratch.
        run: |
          sudo apt-get update # Get the latest info on available software
          sudo apt-get install -y build-essential libprotobuf-dev protobuf-compiler # Install the tools

      - name: Clean and Reinstall Ruby Gems
        # This step forces all Ruby gems, especially google-protobuf, to be rebuilt.
        run: |
          rm -rf vendor/bundle || true # Remove old Ruby gems to ensure a fresh start
          bundle config set --local build.sass-embedded "--disable-install-bundled-compiler" # Specific setting for sass-embedded
          bundle config set --local build.google-protobuf "--with-system-libs" # Tell google-protobuf to use the system libraries we just installed
          bundle install --full-index --jobs 4 --retry 3 --redownload # Install all gems, forcing a fresh download and build

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site