name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.0'

      - name: Install build dependencies and Protocol Buffers library
        # Install compilers (build-essential) AND the Protocol Buffers development library (libprotobuf-dev)
        # to ensure google-protobuf can compile its native extension correctly.
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libprotobuf-dev

      - name: Verify libprotobuf-dev installation (DEBUGGING)
        # This step is for debugging to confirm libprotobuf-dev is actually installed.
        run: dpkg -s libprotobuf-dev || echo "libprotobuf-dev not found, check previous step!"

      - name: Clean and Bundle Install (Force Native Compilation)
        run: |
          # Remove any previous bundle installation to ensure a completely fresh start.
          rm -rf vendor/bundle || true

          # Configure sass-embedded to not use its bundled compiler,
          # as this can sometimes cause issues with its protobuf dependency.
          bundle config set --local build.sass-embedded "--disable-install-bundled-compiler"

          # Explicitly tell google-protobuf to use system libraries for compilation.
          # This, combined with `libprotobuf-dev` above, should ensure a correct build.
          bundle config set --local build.google-protobuf "--with-system-libs"

          # Perform a fresh bundle install.
          # --full-index: Ensures Bundler checks the latest gem info.
          # --jobs 4 --retry 3: For faster and more robust installation.
          # --redownload: This is the correct, modern equivalent of `--force`.
          #               It crucially tells Bundler to re-download and re-install/re-compile all gems,
          #               even if they appear to be present or cached. This is vital for native extensions.
          bundle install --full-index --jobs 4 --retry 3 --redownload

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site