name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.0' # Keep this

      - name: Bundle Install (Force Rebuild)
        run: bundle config set --local build.sass-embedded "--enable-local-binaries --disable-install-bundled-compiler" && bundle install --jobs 4 --retry 3
        # The above line tells Bundler to install the sass-embedded gem,
        # but to ensure it uses a local compiler rather than potentially
        # trying to download a pre-built one that might conflict.
        # The `jobs` and `retry` flags are good practice for CI.


      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site