name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.0'

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential
        # This ensures compilers and development headers are available for native extensions.

      - name: Clean RubyGems cache and installed gems (aggressive clean)
        run: |
          gem pristine --all # Rebuilds all default and installed gems from their original state
          rm -rf vendor/bundle || true # Remove existing bundled gems if any
          bundle clean --force # Clean up unused gems from previous installations

      - name: Bundle Install (Force Rebuild All Gems)
        run: |
          bundle config set --local build.sass-embedded "--disable-install-bundled-compiler"
          bundle config set --local build.google-protobuf "--disable-install-bundled-compiler"
          bundle install --full-index --jobs 4 --retry 3 --force
          # The --force flag here is on bundle install itself, which is more aggressive
          # and should compel ALL gems, including native extensions, to be re-installed/re-compiled.

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site