name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main # Or your main branch name, e.g., master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.0' # Use a Ruby version compatible with Jekyll 4.x and your Gemfile
          bundler-cache: true # Installs gems from Gemfile.lock

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # Action for deploying to gh-pages branch
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site # The directory Jekyll builds your site into
          # If you are deploying to a project page (username.github.io/repo-name),
          # you might need to adjust publish_branch: gh-pages
          # If it's a user/organization page (username.github.io), publish_branch: main is usually correct
          # For typical user/organization pages, publish_branch defaults to gh-pages if not set,
          # but often main is used as the publish branch in repository settings.
          # Check your GitHub Pages settings to confirm the publish branch.
